# Generated by Django 6.0.3 on 2026-05-01 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='idx_address_user_default'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['text'], name='idx_address_text'),
        ),
    ]
