# Generated by Django 6.0.3 on 2026-05-01 11:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_idx_address_user_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Телефон'),
        ),
    ]
