# Generated by Django 6.0.3 on 2026-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_text_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('courier', 'Курьер')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
