# Generated by Django 6.0.3 on 2026-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.IntegerField(blank=True, default=0, verbose_name='Вес (грамм)'),
        ),
    ]
