# Generated by Django 6.0.3 on 2026-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_menuitem_full_description_menuitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(blank=True, default=0, verbose_name='Калории (ккал)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, verbose_name='Белки (г)'),
        ),
    ]
