# Generated by Django 6.0.3 on 2026-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitem_calories_menuitem_carbs_menuitem_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок'),
        ),
    ]
