# Generated by Django 6.0.3 on 2026-05-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='category_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='menuitem_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='menuitem_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('calories__gte', 0)), name='menuitem_calories_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('proteins__gte', 0)), name='menuitem_proteins_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('fats__gte', 0)), name='menuitem_fats_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('carbs__gte', 0)), name='menuitem_carbs_non_negative'),
        ),
    ]
