# Generated by Django 6.0.3 on 2026-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_category_order_non_negative_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='idx_category_active_order'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='idx_menuitem_cat_available'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available', 'price'], name='idx_menuitem_available_price'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='idx_menuitem_name'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available', '-created_at'], name='idx_menuitem_cat_avail_created'),
        ),
    ]
