# Generated by Django 6.0.3 on 2026-05-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_total_non_negative_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
        -- Защита от изменения завершённых/отменённых заказов
        -- Функция триггера
        CREATE OR REPLACE FUNCTION trg_protect_finalized_order()
        RETURNS TRIGGER AS $$
        BEGIN
            -- Если старый статус был 'completed' или 'cancelled', а новый отличается — блокируем
            IF OLD.status IN ('completed', 'cancelled') AND NEW.status != OLD.status THEN
                RAISE EXCEPTION 'Нельзя изменить статус завершённого или отменённого заказа (Заказ #%)', OLD.id;
            END IF;

            -- Автоматически обновляем updated_at (хотя Django делает это сам, но для надёжности)
            NEW.updated_at = CURRENT_TIMESTAMP;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        -- Сам триггер
        DROP TRIGGER IF EXISTS trg_protect_finalized_order ON orders_order;
        CREATE TRIGGER trg_protect_finalized_order
        BEFORE UPDATE ON orders_order
        FOR EACH ROW
        EXECUTE FUNCTION trg_protect_finalized_order();
        """,

            reverse_sql="""
        -- Откат: удаляем триггер и функцию
        DROP TRIGGER IF EXISTS trg_protect_finalized_order ON orders_order;
        DROP FUNCTION IF EXISTS trg_protect_finalized_order();
        """
        ),
    ]
