# Generated by Django 6.0.3 on 2026-05-01 11:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_idx_order_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Телефон'),
        ),
    ]
