# Generated by Django 6.0.3 on 2026-05-08 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_courier_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_status_valid_choice',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'preparing', 'packing', 'delivering', 'completed', 'cancelled'])), name='order_status_valid_choice'),
        ),
    ]
