# Generated by Django 6.0.3 on 2026-05-08 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_order_status_valid_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_status_valid_choice',
        ),
        migrations.AddField(
            model_name='order',
            name='courier_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Курьер доставил'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Клиент подтвердил'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparing', 'Готовится'), ('packing', 'Упаковываем'), ('delivering', 'В доставке'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'preparing', 'packing', 'delivering', 'awaiting_confirmation', 'completed', 'cancelled'])), name='order_status_valid_choice'),
        ),
    ]
